config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "about", to: "pages#about"
  get "contact", to: "pages#contact"
  get "inventory", to: "pages#inventory"
  get "product", to: "pages#product"

  resources :items, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :sub_categories, only: [:index, :show]

  get "featured", to: "items#featured"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_one_attached :photo
  has_many :sub_categories
  has_many :items
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many_attached :photos
  belongs_to :category
  belongs_to :sub_category, optional: true
  validates :title, :description, :price, :brand, :category, :photos, presence: true
  # validates :sub_category, inclusion: { in: ["Forestry", "Flatbeds", "Vans", "Vocational","Highway tractors", "Cab and Chassis", "Construction", "Agriculture", "Engine parts", "Fuel and Hydraulic", "Tanks and Accessories", "Gauges", "Truck", "Equipment"] }
  # validates :category, inclusion: { in: ["Trucks", "Trailers", "Equipment", "Attachments", "Parts", "Misc"] }
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
  has_many :items
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def featured
    @featured = Item.where(featured: true)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home, :about, :contact, :inventory, :product ]

  def home
  end

  def about
  end

  def contact
  end

  def inventory
  end

  def product
  end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  def index
    @sub_categories = SubCategory.all
  end

  def show
    @sub_ategory = SubCategory.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<h2 class="mt-5 mb-5 text-center">Select a category</h2>
<div class="categories-row m-4">
  <div class="inventory-square" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(https://res.cloudinary.com/mberthier/image/upload/v1615952317/pexels-sergio-souza-2805321_odbmcz.jpg)">
    <%= link_to items_path do %>
      All
    <% end %>
  </div>
  <div class="inventory-square" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(https://res.cloudinary.com/mberthier/image/upload/v1606300531/mx0ppczvqku0e7exfbxxddr2xjha.jpg)">
    <%= link_to featured_path do %>
      Featured
    <% end %>
  </div>

  <% @categories.each do |category| %>
      <div class="inventory-square" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url('<%= cl_image_path category.photo.key %>')">
        <%= link_to category_path(category) do %>
          <%= category.name %>
        <% end %>
      </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="hero-banner-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @category.photo.key %>')">
  <h1><%= @category.name %></h1>
</div>

<div class="container">
  <% if @category.items.count == 0 %>
    <p style="text-align: center; margin: 50px 0 50px 0; font-size: 20px;">We don't have any <%= @category.name %> at the moment. Be sure to check back later.</p>
  <% else %>
    <h4 class="mt-5 mb-3">All Products (<%= @category.items.count %>)</h4>
    <div class="row-items">
      <% @category.items.each do |item| %>
        <%= link_to(item_path(item), class: "category-item") do %>
          <div class="category-image" style="background-image: url('<%= cl_image_path item.photos.first.key %>')"></div>
          <div class="content-item">
            <p class="title"><%= "#{item.brand} #{item.title}" %></p>
            <p class="description"><%= item.description.truncate(115, separator: ' ',omission: '... (See More)') %></p>
            <% if item.price == 0 %>
              <p class="price">Contact for pricing</p>
            <% else %>
              <p class="price">$<%= item.price.to_s.reverse.scan(/\d{3}|.+/).join(",").reverse %></p>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <div class="contact">
    <h4 style="margin: 50px 0;">Looking for something specific?</h4>
    <%= link_to contact_path do %>
      <button type="button" class="btn btn-dark btn-lg">Contact Us</button>
    <% end %>
  </div>

</div>

app/views/items/_featured.html.erb
<div class="featured">
  <h2>Featured items</h2>
  <div class="container">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <% @featured = Item.where(featured: true) %>
        <% @featured.each_with_index do |item, index| %>
          <% if index == 0 %>
            <div class="carousel-item active">
              <%= link_to item_path(item) do %>
                <div class="featured-item">
                  <div class="featured-image" style="background-image: url('<%= cl_image_path item.photos[0].key %>')"></div>
                  <div class="featured-content-item">
                    <p class="title"><%= "#{item.brand} #{item.title}" %></p>
                    <p class="description"><%= item.description.truncate(115, separator: ' ',omission: '... (See More)') %></p>
                    <% if item.description.length >= 115 %>
                      <p style="text-decoration: underline;">See More</p>
                    <% end %>
                    <% if item.price == 0 %>
                      <p class="price">Contact for pricing</p>
                    <% else %>
                      <p class="price">$<%= item.price.to_s.reverse.scan(/\d{3}|.+/).join(",").reverse %></p>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          <% else %>
            <div class="carousel-item">
              <%= link_to item_path(item) do %>
                <div class="featured-item">
                  <div class="featured-image" style="background-image: url('<%= cl_image_path item.photos[0].key %>')"></div>
                  <div class="featured-content-item">
                    <p class="title"><%= "#{item.brand} #{item.title}" %></p>
                    <p class="description"><%= item.description.truncate(115, separator: ' ',omission: '... (See More)') %></p>
                    <% if item.price == 0 %>
                      <p class="price">Contact for pricing</p>
                    <% else %>
                      <p class="price">$<%= item.price.to_s.reverse.scan(/\d{3}|.+/).join(",").reverse %></p>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>

app/views/items/featured.html.erb
<div class="hero-banner-category" style="background-image: url(https://res.cloudinary.com/mberthier/image/upload/v1606400531/mx0ppczvqku0e7exfbxxddr2xjha.jpg)">
  <h1>Featured</h1>
</div>

<div class="container mt-5 mb-5">
  <div class="row-items">
    <% @featured.each do |item| %>
      <%= link_to(item_path(item), class: "category-item") do %>
        <div class="category-image" style="background-image: url('<%= cl_image_path item.photos[0].key %>')"></div>
        <div class="content-item">
          <p class="title"><%= "#{item.brand} #{item.title}" %></p>
          <p class="description"><%= item.description.truncate(115, separator: ' ',omission: '... (See More)') %></p>
          <% if item.price == 0 %>
            <p class="price">Contact for pricing</p>
          <% else %>
            <p class="price">$<%= item.price.to_s.reverse.scan(/\d{3}|.+/).join(",").reverse %></p>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<div class="hero-banner-category" style="background-image: url(https://res.cloudinary.com/mberthier/image/upload/v1615952317/pexels-sergio-souza-2805321_odbmcz.jpg)">
  <h1>All</h1>
</div>

<div class="container mt-5 mb-5">
  <div class="row-items">
    <% @items.each do |item| %>
      <%= link_to(item_path(item), class: "category-item") do %>
        <div class="category-image" style="background-image: url('<%= cl_image_path item.photos.first.key %>')"></div>
        <div class="content-item">
          <p class="title"><%= "#{item.brand} #{item.title}" %></p>
          <p class="description"><%= item.description.truncate(115, separator: ' ',omission: '... (See More)') %></p>
          <% if item.price == 0 %>
            <p class="price">Contact for pricing</p>
          <% else %>
            <p class="price">$<%= item.price.to_s.reverse.scan(/\d{3}|.+/).join(",").reverse %></p>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class="product">
    <div class="product-left">
      <div class="carousel-mobile">
        <div id="carouselExample1" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <% @item.photos.each_with_index do |photo, index| %>
              <% if index == 0 %>
                <div class="carousel-item active">
                  <div class="modal-image" data-toggle="modal" data-target="#exampleModalCenter" style="background-image: url('<%= cl_image_path @item.photos[0].key %>')"></div>
                </div>
              <% else %>
                <div class="carousel-item">
                  <div class="modal-image" data-toggle="modal" data-target="#exampleModalCenter" style="background-image: url('<%= cl_image_path @item.photos[index].key %>')"></div>
                </div>
              <% end %>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExample1" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExample1" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <div class="img-main" data-toggle="modal" data-target=".bd-example-modal-lg" style="background-image: url('<%= cl_image_path @item.photos[0].key %>')"></div>
        <div class="img-row">
          <% if @item.photos.count >= 4 %>
            <div class="img-sec" data-toggle="modal" data-target=".bd-example-modal-lg" style="background-image: url('<%= cl_image_path @item.photos[1].key %>')"></div>
            <div class="img-sec" data-toggle="modal" data-target=".bd-example-modal-lg" style="background-image: url('<%= cl_image_path @item.photos[2].key %>')"></div>
            <div class="img-sec" data-toggle="modal" data-target=".bd-example-modal-lg" style="background-image: url('<%= cl_image_path @item.photos[3].key %>')"></div>
          <% else %>
            <div class="img-sec" data-toggle="modal" data-target=".bd-example-modal-lg" style="background-image: url(https://res.cloudinary.com/mberthier/image/upload/v1614229357/pexels-pixabay-210881_1_k2zoju.jpg)"></div>
            <div class="img-sec" data-toggle="modal" data-target=".bd-example-modal-lg" style="background-image: url(https://res.cloudinary.com/mberthier/image/upload/v1614229357/pexels-pixabay-210881_1_k2zoju.jpg)"></div>
            <div class="img-sec" data-toggle="modal" data-target=".bd-example-modal-lg" style="background-image: url(https://res.cloudinary.com/mberthier/image/upload/v1614229357/pexels-pixabay-210881_1_k2zoju.jpg)"></div>
          <% end %>
        </div>
    </div>
    <div class="product-right">
      <div class="product-info">
        <p class="product-title"><%="#{@item.year} #{@item.brand} #{@item.title}"%></p>
        <% if  @item.sub_category %>
          <p class="product-tag"><%= @item.sub_category.name%><i class="fa fa-tags" style="font-size: 16px; margin-left: 8px;"></i></p>
        <% end %>
        <p class="product-descritpion"><%= @item.description %></p>
        <% if  @item.price == 0 %>
          <p class="product-price">Contact for pricing</p>
        <% else %>
          <p class="product-price">$<%= @item.price.to_s.reverse.scan(/\d{3}|.+/).join(",").reverse %></p>
        <% end %>
      </div>
      <div class="inquire">
        <h3>Inquire about this item</h3>
        <div class="inquire-cta">
          <a class="btn btn-dark btn-lg btn-lg" style="width: 125px;" href="tel:250-991-2830">Call us</a>
          <a class="btn btn-outline-dark btn-lg" style="width: 125px;" href="mailto:johnston8474@gmail.com">Email us</a>
<!--           <div class="phone"><p><a href="tel:250-991-2830">(250) 991-2830</a></p></div> -->
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div id="carouselExample2" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <% @item.photos.each_with_index do |photo, index| %>
            <% if index == 0 %>
              <div class="carousel-item active">
                <div class="modal-image" data-toggle="modal" data-target="#exampleModalCenter" style="background-image: url('<%= cl_image_path @item.photos[0].key %>')"></div>
              </div>
            <% else %>
              <div class="carousel-item">
                <div class="modal-image" data-toggle="modal" data-target="#exampleModalCenter" style="background-image: url('<%= cl_image_path @item.photos[index].key %>')"></div>
              </div>
            <% end %>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExample2" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExample2" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JohnstonEquipment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="hero-banner-about">
  <h1>About us</h1>
</div>
<div class="container">
  <div class="main">
    <div class="intro-left">
      <div class="content-start">
        <h2>Over 45 years in the business</h2>
        <p>Johnston Equipment started in 1979 in Quesnel, B.C. as a family owned and operated business and remains as such to this day.</p>
        <p>For over 35 years, we specialized in dis-assembly of late model class eight trucks, providing high-quality used parts to dealers, fleets, insurance companies and end-users.</p>
        <p>In 2015, we took the opportunity to pass on the used parts division of our company to Keith Mechanical Services. We now continue to sell heavy trucks, trailers, attachments, equipment, and new aftermarket parts to our valued customers, both within Canada and internationally.</p>
      </div>
    </div>
    <div class="intro-right">
      <img class="intro-image" src="https://res.cloudinary.com/mberthier/image/upload/w_1000,ar_16:9,c_fill,g_auto,e_sharpen/v1614230124/IMG_4912_1_pepgaa.jpg" alt="">
    </div>
  </div>

  <div class="last-paragraph">
    <p>You can take a look at our selection of available inventory by following the links below. Otherwise, you can <%= link_to "get in touch", contact_path %> to inquire about items not listed on our website or simply to say hello.</p>
  </div>

  <h2>Discover our inventory</h2>
  <div class="categories-row">
    <% trucks = Category.find_by(name: "Trucks")  %>
      <div class="category-square" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%= cl_image_path trucks.photo.key %>')">
        <%= link_to category_path(trucks.id) do %>
          Trucks
        <% end %>
      </div>
    <% equipment = Category.find_by(name: "Equipment")  %>
      <div class="category-square" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%= cl_image_path equipment.photo.key %>')">
        <%= link_to category_path(equipment.id) do %>
          Equipment
        <% end %>
      </div>
    <% parts = Category.find_by(name: "Parts")  %>
      <div class="category-square" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%= cl_image_path parts.photo.key %>')">
        <%= link_to category_path(parts.id) do %>
          Parts
        <% end %>
      </div>
    <% trailers = Category.find_by(name: "Trailers")  %>
      <div class="category-square" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%= cl_image_path trailers.photo.key %>')">
        <%= link_to category_path(trailers.id) do %>
          Trailers
        <% end %>
      </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://res.cloudinary.com/mberthier/image/upload/v1606820158/IMG_3449_vvlgqf.jpg);">
  <div class="container-home">
    <h1>Get back on the road</h1>
    <%= link_to categories_path do %>
      <button type="button" class="home-btn">See Inventory</button>
    <% end %>
  </div>
</div>

<div class="categories-row">
  <% trucks = Category.find_by(name: "Trucks")  %>
    <div class="category-square" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%= cl_image_path trucks.photo.key %>')">
      <%= link_to category_path(trucks.id) do %>
        Trucks
      <% end %>
    </div>
  <% equipment = Category.find_by(name: "Equipment")  %>
    <div class="category-square" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%= cl_image_path equipment.photo.key %>')">
      <%= link_to category_path(equipment.id) do %>
        Equipment
      <% end %>
    </div>
  <% parts = Category.find_by(name: "Parts")  %>
    <div class="category-square" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%= cl_image_path parts.photo.key %>')">
      <%= link_to category_path(parts.id) do %>
        Parts
      <% end %>
    </div>
  <% trailers = Category.find_by(name: "Trailers")  %>
    <div class="category-square" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%= cl_image_path trailers.photo.key %>')">
      <%= link_to category_path(trailers.id) do %>
        Trailers
      <% end %>
    </div>
</div>

<div class="container mt-5">
  <div class="usp">
    <div class="usp-left">
      <div class="usp-image" style="background-image: url(https://res.cloudinary.com/mberthier/image/upload/v1616634172/IMG_8044_u2lm1u.png)"></div>
    </div>
    <div class="usp-right">
      <div class="content">
        <h2>Carefully-sourced parts, trucks & equipment</h2>
        <p>We specialise in selling heavy trucks, trailers, attachments, equipment, and new aftermarket parts to our valued customers.</p>
        <p>We are proudly Canadian and have been supporting both local and international clients with their commercial vehicle needs since 1979.</p>
      </div>
    </div>
  </div>
</div>

<%= render "items/featured", item: @item %>

<div class="parallax"></div>
<div class="parallax-mobile"></div>


<div class="testimonials">
  <h2>What others say about us</h2>
  <div class="container">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="testimonial">
            <p class="quote">“I’ve been working with Rob for over 20 years. He has incredible knowledge of the industry and I would 100% recommend his services.”</p>
            <p class="job">James, HD Repair shop </p>
          </div>
        </div>
        <div class="carousel-item">
          <div class="testimonial">
            <p class="quote">“Johnston Equipment is always a pleasure to work with. They are great people and I know that the equipment they source for me will be good quality and do the job well. Thanks Rob and Lisa!”</p>
            <p class="job">Mike, Fleet owner</p>
          </div>
        </div>
        <div class="carousel-item">
          <div class="testimonial">
            <p class="quote">“I can’t say a bad thing about Johnston Equipment. Run by great people and Rob is an expert in what he’s doing, so you can trust his advice. Will be getting in touch with them again soon. ”</p>
            <p class="job">Keith, Independent trucker</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="contact">
  <h2>Can’t find what you are looking for?</h2>
  <%= link_to contact_path do %>
    <button type="button" class="btn btn-dark btn-lg">Contact Us</button>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-top">
    <div class="footer-copyright">
      Copyright © 2021 Hallis Holdings Ltd
    </div>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "JELogo2.png", alt: "alttext" %>
    <% end %>
    <div class="footer-links">
      <%= link_to "Inventory", categories_path %>
      <%= link_to "About Us", about_path %>
      <%= link_to "Contact", contact_path %>
    </div>
  </div>
  <div class="footer-bottom">
    Website proudly developed by Madfrog 🐸
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "JELogo2.png", alt: "alttext" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Inventory", categories_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About us", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag("rob_lunlsq.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user.admin %>
              <%= link_to "Admin", rails_admin_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Inventory", categories_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About us", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/sub_categories/index.html.erb
<% @sub_categories.each do |sub_category| %>
  <li><%= link_to sub_category.name, sub_category_path(sub_category) %></li>
<% end %>